### ISSUE TITLE
dashboard message error 

### ISSUE THREAD

**Issue by ghandour87** [abedputra/Attendance-login-system#13]
hello , after installing this script  using localhost  an error alert : DataTables warning: table id=data-table - Ajax error. For more information about this error, please see http://datatables.net/tn/7. 
how can i fix it? specially when adding new user since this error prevents me to add a new employee.
using WAMP server , PHP 7.2
best regards thanks .

**Comment by abedputra** [comment]
Please check here
https://github.com/abedputra/Attendance-login-system/issues/10

Thanks

**Comment by ghandour87** [comment]
good night . thanks for your quick response ,
i followed what you request in the ticket #10 , but there is no response, can you please give me your feed back about this issue . here is the screen shoots about the installing path of the composer and the message error.
and thanks for your full support dear 
![Untitled1](https://user-images.githubusercontent.com/75255410/100671234-ce8e9c00-3368-11eb-8f79-1f479e6665fc.png)
![Untitled2](https://user-images.githubusercontent.com/75255410/100671266-da7a5e00-3368-11eb-9085-6aed3ada4990.png)
![Untitled3](https://user-images.githubusercontent.com/75255410/100671270-dd754e80-3368-11eb-8144-a93b00feca4a.png)
