### ISSUE TITLE
One of the Worst Instructions (of not working code)

### ISSUE THREAD

**Issue by enverahmet** [abedputra/Attendance-login-system#3]
I did NOT be able to install it. Idea is bright, but instructions are terrible! Main.php directs to a non-existing directory (main/login/).
Seems like it needs more than fine-tuning. I really would like to see it in action.

**Comment by abedputra** [comment]
Hi,
The reason why redirect to main/login because this system is backend, and this system created just for manage the employee.

If your page (main/login) is blank, please check the htaccess.

Thanks

**Comment by b4allb4u** [comment]
Hello Sir

![image](https://user-images.githubusercontent.com/24243794/66470935-29e83580-eaa8-11e9-9709-65cba68daec9.png)

Please help me on this issue..

**Comment by enverahmet** [comment]
Hi Abed,
Seems like your sql query is misguided, but I cannot be sure where the
problem lies without checking your source code.

**Comment by abedputra** [comment]
Hi,
The problem not from my code. The problem is when import SQL the table not imported.

I have discussed it with him.

Thanks

**Comment by enverahmet** [comment]
It's good to hear that you solved the issue.
