### ISSUE TITLE
Main Page issue

### ISSUE THREAD

**Issue by b4allb4u** [abedputra/Attendance-login-system#7]
Hello Sir

![image](https://user-images.githubusercontent.com/24243794/66470935-29e83580-eaa8-11e9-9709-65cba68daec9.png)

Please help me on this issue..

_Originally posted by @b4allb4u in https://github.com/abedputra/Attendance-login-system/issues/3#issuecomment-539927460_

**Comment by abedputra** [comment]
as you can see the error said "settings doesn't exist", that's mean the settings table not properly imported. so please check your database and check is the settings table exists or not.

**Comment by b4allb4u** [comment]
You are really super boss! TQQQQQ So much for your support.
