### ISSUE TITLE
Lowercase route profileuser won't work

### ISSUE THREAD

**Issue by theapu** [abedputra/Attendance-login-system#8]
You have used controller ProfileUser. The url https://domain.com/profileuser does not work when hosted in linux server with this controller naming. This may work in windows hosted servers.
As per Codeigniter recommended naming scheme controller names should start with capital letter but remaining letters should be lowercase. Changing ProfileUser.php to Profileuser.php and changing class ProfileUser to class Profileuser fixed the url problem for me in Linux. Kindly updated.

**Comment by abedputra** [comment]
Hi,

Thanks for the report.
We have fixed that, and also please check out, our new system with last version v3 CI.
[6318685acdefb631c3c3acf87dd76a0471a9e85d](https://github.com/abedputra/Attendance-login-system/commit/6318685acdefb631c3c3acf87dd76a0471a9e85d)

Thanks
