### ISSUE TITLE
Ajax Error in History QR and Users List

### ISSUE THREAD

**Issue by robbytriadi** [abedputra/Attendance-login-system#9]
Hi @abedputra 

Thank you for your simple system that powerful for me :)
I will report an error when I choose History QR and User List menu, appears:

![image](https://user-images.githubusercontent.com/49820621/92867098-765f9200-f42a-11ea-836c-641a9e554326.png)

Please help
Thank you

**Comment by abedputra** [comment]
Have you done composer update?

Thanks

**Comment by leolf9** [comment]
Hi, i have the same problem, my composer is updated
![Captura de pantalla (1)](https://user-images.githubusercontent.com/71472942/93540920-c05ce200-f91a-11ea-87c0-fa46d5f9fea4.png)

**Comment by abedputra** [comment]
related https://github.com/abedputra/Attendance-login-system/issues/10
